### PR TITLE
adding content to Tutorial 00 related to #72

### PR DESCRIPTION
**Pull request by virdi**
This updates Tutorial 00, as discussed in #72

### CODE REVIEW

**Comment by jules32** [comment]
This looks good @virdi! I really like the "Steps" and "Discussion" sections, that is a great idea.

One question: with the Git plug-in, will they be prompted to configure their username and password, and if so do we need to cover that? Or is that somehow automatic?

**Comment by jules32** [comment]
I'll let Luis merge after he has a look/adds updates

**Comment by virdi** [comment]
> This looks good @virdi! I really like the "Steps" and "Discussion" sections, that is a great idea.
> 
> One question: with the Git plug-in, will they be prompted to configure their username and password, and if so do we need to cover that? Or is that somehow automatic?

For `clone` step, it won't prompt for github credentials. When they modify files in their cloned copy (fork), they will be prompted. Do we want to cover setting up credentials in Tutorial 00? If so, do we go the "access token" route and further, do we do it via command line?

I can include that if you want, and/or redirect them to the clinic chapter for self-guided set up. If we have time left, we can go over that too. Thoughts @betolink @jules32 ?

**Comment by virdi** [comment]
Just pushed some more minor edits (plus screenshots)

**Pull request merged**
