### PR TITLE
add numpy

### PR DESCRIPTION
**Pull request by andypbarrett**
add numpy

### CODE REVIEW

**Comment by jules32** [comment]
@andypbarrett @asteiker did I understand you're still planning to push to this PR? I'll wait to merge until I hear from you (or you can both merge as well too).

**Comment by andypbarrett** [comment]
Yes, I'm still pushing

**Comment by andypbarrett** [comment]
This is my final push.  Cells below the plot can be removed.

**Comment by jules32** [comment]
deleting branch after merge

**Pull request merged**
